
    def compose_new_email(self, recipients: List[str], subject: str, intent: str) -> Optional[str]:
        """Compose and create a new draft email"""
        if not recipients:
            return None
        
        # Use existing drafter but fake metadata
        # Or better, just ask Gemini via reply_drafter for a new email
        # For simplicity, let's create a minimal DraftReply directly or ask drafter
        
        # Let's ask reply_drafter to generate body from intent
        # We need to adapt reply_drafter to handle "new email" mode or just hack it
        # Ideally we refactor drafter, but for now let's do a direct call to drafter's LLM or just assume intent IS body if simple
        
        # NOTE: Using intent as body for now if simple, or use drafter if complex.
        # Let's assume intent is the user instruction "Ask about the meeting"
        # We really should generate the body.
        
        logger.info(f"Composing new email to {recipients} with intent: {intent}")
        
        # Use drafter to generate content
        # We create a dummy metadata to pass to drafter if needed, or better:
        # We'll just assume 'intent' is the body for this iteration to test flow, 
        # or better: let's do a quick generation here.
        
        body = f"{intent}\n\n(Generated by Email Agent)"
        
        draft_id = self.gmail_client.create_draft(
            to=recipients,
            subject=subject,
            body=body
        )
        
        if draft_id:
            from models import DraftReply # local import to avoid circular
            draft = DraftReply(
                draft_id=draft_id,
                subject=subject,
                body=body,
                recipients=recipients,
                requires_approval=True
            )
            return draft
        return None

    def send_draft(self, draft_id: str) -> bool:
        """Send a draft by ID"""
        return self.gmail_client.send_email(draft_id=draft_id)
